# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-a89867d9-0b33-4d78-ad16-439b29c0c898";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-a89867d9-0b33-4d78-ad16-439b29c0c898".device = "/dev/disk/by-uuid/a89867d9-0b33-4d78-ad16-439b29c0c898";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/4524-4377";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-715a8e9d-0c95-4c58-9a99-5d2eb22499d7"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

}
